LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := Cobalt
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_PACKAGE_NAME := Cobalt
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PACKAGE)
